kind: Cluster
name: omni-contrib
talos:
  version: v1.10.5
kubernetes:
  version: 1.33.2
features:
  enableWorkloadProxy: true
patches:
  - name: longhorn-kernel-modules
    file: patches/longhorn-kernel-modules.yaml
  - name: longhorn-rw
    file: patches/longhorn-rw.yaml
systemExtensions:
  - siderolabs/iscsi-tools
  - siderolabs/util-linux-tools    
---
kind: ControlPlane
machineClass:
  name: omni-contrib-controlplane
  size: 3
patches:
  - name: argocd
    file: patches/argocd.yaml
  - name: monitoring
    file: patches/monitoring.yaml
  - name: longhorn-kernel-modules
    file: patches/longhorn-kernel-modules.yaml
  - name: longhorn-rw
    file: patches/longhorn-rw.yaml
---
kind: Workers
name: workers
machineClass:
  name: omni-contrib-workers
  size: unlimited
patches:
  - name: longhorn-kernel-modules
    file: patches/longhorn-kernel-modules.yaml
  - name: longhorn-rw
    file: patches/longhorn-rw.yaml    