apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-backup-target
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  syncPolicy:
    syncOptions:
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 2m
  project: default
  source:
    repoURL: https://github.com/BenjaminDavison/omni-argo.git
    targetRevision: HEAD
    path: omni/apps/longhorn/backup-target
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  ignoreDifferences:
    - group: longhorn.io
      kind: BackupTarget
      jsonPointers:
        - /spec/backupTargetURL
