apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.8.0 # Replace with the Longhorn version you'd like to install or upgrade to
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
          longhorn-frontend:
            service:
              annotations:
                omni-kube-service-exposer.sidero.dev/port: "50083"
                omni-kube-service-exposer.sidero.dev/label: Longhorn
          metrics:
            serviceMonitor:
              enabled: true
          defaultSettings:
            defaultDataPath: /var/mnt/storage
            createDefaultDiskLabeledNodes: true
            replicaAutoBalance: enabled
          persistence:
            defaultClass: true
            defaultClassReplicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  ignoreDifferences:
    - group: longhorn.io
      kind: BackupTarget
      jsonPointers:
        - /spec/backupTargetURL
