apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.8.0 # Replace with the Longhorn version you'd like to install or upgrade to
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
          longhornUI:
            service:
              annotations:
                omni-kube-service-exposer.sidero.dev/port: "50083"
                omni-kube-service-exposer.sidero.dev/label: Longhorn
          defaultSettings:
            defaultDataPath: /var/lib/longhorn
          persistence:
            defaultClass: true
            defaultClassReplicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
