machine:
  sysctls:
    vm.nr_hugepages: "1024"
  kernel:
    modules:
      - name: nbd
      - name: iscsi_tcp
      - name: configfs
      - name: nvme_tcp
      - name: vfio_pci
#     - name: uio_pci_generic      
