apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: test-metallb
  annotations:
    metallb.io/address-pool: production-public-ips
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
