apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-alerts
  namespace: monitoring
  labels:
    app: prometheus
    release: kube-prometheus-stack
data:
  longhorn-alerts.yaml: |
    groups:
    - name: longhorn.rules
      rules:
      - alert: LonghornVolumeDegraded
        expr: longhorn_volume_status{state="degraded"} == 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Longhorn volume {{ $labels.volume_name }} is degraded"
          description: "Volume {{ $labels.volume_name }} has been in degraded state for more than 5 minutes"

      - alert: LonghornVolumeFaulted
        expr: longhorn_volume_status{state="faulted"} == 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Longhorn volume {{ $labels.volume_name }} is faulted"
          description: "Volume {{ $labels.volume_name }} is in faulted state"

      - alert: LonghornVolumeDetached
        expr: longhorn_volume_status{state="detached"} == 1
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Longhorn volume {{ $labels.volume_name }} is detached"
          description: "Volume {{ $labels.volume_name }} has been detached for more than 10 minutes"

      - alert: LonghornNodeDown
        expr: longhorn_node_status{condition="ready"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Longhorn node {{ $labels.node_name }} is down"
          description: "Longhorn node {{ $labels.node_name }} has been down for more than 5 minutes"

      - alert: LonghornVolumeSpaceUsage
        expr: (longhorn_volume_actual_size_bytes / longhorn_volume_size_bytes) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Longhorn volume {{ $labels.volume_name }} is running out of space"
          description: "Volume {{ $labels.volume_name }} is using more than 80% of its allocated space"
