kube-prometheus-stack:
  # NOTE: These must be set manually to the control plane IP addresses
  #kubeEtcd:
  #  endpoints:
  #    - x.y.z.a
  #    - x.y.z.b
  #    - x.y.z.c
  kubeControllerManager:
    service:
      selector:
        k8s-app: kube-controller-manager
  kubeScheduler:
    service:
      selector:
        k8s-app: kube-scheduler
  alertmanager:
    alertmanagerspec:
      storage:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 150Gi
      # Load custom alert rules
      ruleSelector:
        matchLabels:
          app: prometheus
          release: kube-prometheus-stack
      # Additional ServiceMonitors
      additionalServiceMonitors:
        - name: longhorn-prometheus-servicemonitor
          selector:
            matchLabels:
              app: longhorn-manager
          namespaceSelector:
            matchNames:
              - longhorn-system
          endpoints:
            - port: manager
              interval: 30s
              path: /metrics
      # Additional PrometheusRules
      additionalPrometheusRulesMap:
        longhorn-alerts:
          groups:
            - name: longhorn.rules
              rules:
                - alert: LonghornVolumeDegraded
                  expr: longhorn_volume_status{state="degraded"} == 1
                  for: 5m
                  labels:
                    severity: warning
                  annotations:
                    summary: "Longhorn volume {{ $labels.volume_name }} is degraded"
                    description: "Volume {{ $labels.volume_name }} has been in degraded state for more than 5 minutes"
                - alert: LonghornVolumeFaulted
                  expr: longhorn_volume_status{state="faulted"} == 1
                  for: 1m
                  labels:
                    severity: critical
                  annotations:
                    summary: "Longhorn volume {{ $labels.volume_name }} is faulted"
                    description: "Volume {{ $labels.volume_name }} is in faulted state"
                - alert: LonghornVolumeDetached
                  expr: longhorn_volume_status{state="detached"} == 1
                  for: 10m
                  labels:
                    severity: warning
                  annotations:
                    summary: "Longhorn volume {{ $labels.volume_name }} is detached"
                    description: "Volume {{ $labels.volume_name }} has been detached for more than 10 minutes"
                - alert: LonghornNodeDown
                  expr: longhorn_node_status{condition="ready"} == 0
                  for: 5m
                  labels:
                    severity: critical
                  annotations:
                    summary: "Longhorn node {{ $labels.node_name }} is down"
                    description: "Longhorn node {{ $labels.node_name }} has been down for more than 5 minutes"
                - alert: LonghornVolumeSpaceUsage
                  expr: (longhorn_volume_actual_size_bytes / longhorn_volume_size_bytes) * 100 > 80
                  for: 5m
                  labels:
                    severity: warning
                  annotations:
                    summary: "Longhorn volume {{ $labels.volume_name }} is running out of space"
                    description: "Volume {{ $labels.volume_name }} is using more than 80% of its allocated space"
  grafana:
    grafana.ini:
      auth:
        disable_login_form: true
        disable_signout_menu: true
      auth.basic:
        enabled: false
      auth.anonymous:
        enabled: true
    # Allow Omni Workload Proxying for this service
    service:
      annotations:
        omni-kube-service-exposer.sidero.dev/port: "50082"
        omni-kube-service-exposer.sidero.dev/label: Grafana
    # Enable dashboard provisioning
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'longhorn'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          updateIntervalSeconds: 10
          allowUiUpdates: true
          options:
            path: /var/lib/grafana/dashboards/longhorn
    dashboards:
      longhorn:
        longhorn-dashboard:
          gnetId: null
          revision: 1
          datasource: prometheus-longhorn
          json: |
            {
              "annotations": {
                "list": [
                  {
                    "builtIn": 1,
                    "datasource": "-- Grafana --",
                    "enable": true,
                    "hide": true,
                    "iconColor": "rgba(0, 211, 255, 1)",
                    "name": "Annotations & Alerts",
                    "type": "dashboard"
                  }
                ]
              },
              "editable": true,
              "gnetId": null,
              "graphTooltip": 0,
              "id": null,
              "links": [],
              "panels": [
                {
                  "aliasColors": {},
                  "bars": false,
                  "dashLength": 10,
                  "dashes": false,
                  "datasource": "prometheus-longhorn",
                  "fieldConfig": {
                    "defaults": {
                      "custom": {}
                    },
                    "overrides": []
                  },
                  "fill": 1,
                  "fillGradient": 0,
                  "gridPos": {
                    "h": 8,
                    "w": 12,
                    "x": 0,
                    "y": 0
                  },
                  "hiddenSeries": false,
                  "id": 1,
                  "legend": {
                    "avg": false,
                    "current": false,
                    "max": false,
                    "min": false,
                    "show": true,
                    "total": false,
                    "values": false
                  },
                  "lines": true,
                  "linewidth": 1,
                  "nullPointMode": "null",
                  "options": {
                    "alertThreshold": true
                  },
                  "percentage": false,
                  "pluginVersion": "7.1.5",
                  "pointradius": 2,
                  "points": false,
                  "renderer": "flot",
                  "seriesOverrides": [],
                  "spaceLength": 10,
                  "stack": false,
                  "steppedLine": false,
                  "targets": [
                    {
                      "expr": "longhorn_volume_actual_size_bytes",
                      "interval": "",
                      "legendFormat": "{{volume_name}}",
                      "refId": "A"
                    }
                  ],
                  "thresholds": [],
                  "timeFrom": null,
                  "timeRegions": [],
                  "timeShift": null,
                  "title": "Volume Actual Size",
                  "tooltip": {
                    "shared": true,
                    "sort": 0,
                    "value_type": "individual"
                  },
                  "type": "graph",
                  "xaxis": {
                    "buckets": null,
                    "mode": "time",
                    "name": null,
                    "show": true,
                    "values": []
                  },
                  "yaxes": [
                    {
                      "format": "bytes",
                      "label": null,
                      "logBase": 1,
                      "max": null,
                      "min": null,
                      "show": true
                    },
                    {
                      "format": "short",
                      "label": null,
                      "logBase": 1,
                      "max": null,
                      "min": null,
                      "show": true
                    }
                  ],
                  "yaxis": {
                    "align": false,
                    "alignLevel": null
                  }
                },
                {
                  "aliasColors": {},
                  "bars": false,
                  "dashLength": 10,
                  "dashes": false,
                  "datasource": "prometheus-longhorn",
                  "fieldConfig": {
                    "defaults": {
                      "custom": {}
                    },
                    "overrides": []
                  },
                  "fill": 1,
                  "fillGradient": 0,
                  "gridPos": {
                    "h": 8,
                    "w": 12,
                    "x": 12,
                    "y": 0
                  },
                  "hiddenSeries": false,
                  "id": 2,
                  "legend": {
                    "avg": false,
                    "current": false,
                    "max": false,
                    "min": false,
                    "show": true,
                    "total": false,
                    "values": false
                  },
                  "lines": true,
                  "linewidth": 1,
                  "nullPointMode": "null",
                  "options": {
                    "alertThreshold": true
                  },
                  "percentage": false,
                  "pluginVersion": "7.1.5",
                  "pointradius": 2,
                  "points": false,
                  "renderer": "flot",
                  "seriesOverrides": [],
                  "spaceLength": 10,
                  "stack": false,
                  "steppedLine": false,
                  "targets": [
                    {
                      "expr": "longhorn_volume_status",
                      "interval": "",
                      "legendFormat": "{{volume_name}}",
                      "refId": "A"
                    }
                  ],
                  "thresholds": [],
                  "timeFrom": null,
                  "timeRegions": [],
                  "timeShift": null,
                  "title": "Volume Status",
                  "tooltip": {
                    "shared": true,
                    "sort": 0,
                    "value_type": "individual"
                  },
                  "type": "graph",
                  "xaxis": {
                    "buckets": null,
                    "mode": "time",
                    "name": null,
                    "show": true,
                    "values": []
                  },
                  "yaxes": [
                    {
                      "format": "short",
                      "label": null,
                      "logBase": 1,
                      "max": null,
                      "min": null,
                      "show": true
                    },
                    {
                      "format": "short",
                      "label": null,
                      "logBase": 1,
                      "max": null,
                      "min": null,
                      "show": true
                    }
                  ],
                  "yaxis": {
                    "align": false,
                    "alignLevel": null
                  }
                }
              ],
              "schemaVersion": 26,
              "style": "dark",
              "tags": ["longhorn"],
              "templating": {
                "list": []
              },
              "time": {
                "from": "now-1h",
                "to": "now"
              },
              "timepicker": {},
              "timezone": "",
              "title": "Longhorn Dashboard",
              "uid": "longhorn",
              "version": 1
            }
