apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

resources:
  - namespace.yaml

helmCharts:
  - name: metallb
    version: 0.15.2
    repo: https://metallb.github.io/metallb
    valuesFile: values.yaml
    namespace: metallb-system
