apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - Chart.yaml
  - values.yaml
  - namespace.yaml
  - ipaddresspool.yaml

helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    version: 0.15.2
    releaseName: metallb
    namespace: metallb-system
    valuesInline:
      metallb:
        layer2:
          enabled: true
        bgp:
          enabled: false
        speaker:
          tolerations:
            - key: node-role.kubernetes.io/master
              operator: Exists
              effect: NoSchedule
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
        controller:
          tolerations:
            - key: node-role.kubernetes.io/master
              operator: Exists
              effect: NoSchedule
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
        prometheus:
          enabled: true
          serviceMonitor:
            enabled: true
            interval: 30s
