# Basic configuration for MetalLB
# You can customize this based on your network requirements

# IP Address Pools - defines the range of IPs MetalLB can assign
ipAddressPools:
  - name: production-public-ips
    addresses:
      - 34.74.243.190/32
      - 34.75.150.195/32
      - 35.196.78.1/32

# Layer 2 Advertisement - enables Layer 2 mode for the IP pools
l2Advertisements:
  - name: production-public-ips-l2
    ipAddressPools:
      - production-public-ips

# Speaker configuration
speaker:
  ignoreExcludeLB: true ### Default is false  
  # Node selector for speaker pods
  nodeSelector: {}
  # Tolerations for speaker pods
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  # ServiceMonitor configuration
  serviceMonitor:
    enabled: false
    interval: 30

# Controller configuration
controller:
  # Node selector for controller pods
  nodeSelector: {}
  # Tolerations for controller pods
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  # ServiceMonitor configuration
  serviceMonitor:
    enabled: false
    interval: 30

# Prometheus monitoring
prometheus:
  enabled: false
  # serviceAccount: "metallb-prometheus"
  # namespace: "monitoring"
  # serviceMonitor:
  #   enabled: true
  #   interval: 30
